### ISSUE TITLE
RSA Padding Oracle

### ISSUE THREAD

**Issue by paragonie-scott** [Cosmicist/AsymmetriCrypt#4]
See https://framework.zend.com/security/advisory/ZF2015-10 it's essentially the same vulnerability

**Comment by paragonie-scott** [comment]
https://github.com/Cosmicist/AsymmetriCrypt/blob/e3eaa30b630c30d68ff9e98a1aff77af72ad5c25/lib/AsymmetriCrypt/Crypter.php#L39 is the offending line of code, but given that it's been 10 months without a response to a severe vulnerability, I'm just going to close this issue.

**Comment by huntr-helper** [comment]
‎‍🛠️ A fix has been provided for this issue. Please reference: https://github.com/418sec/AsymmetriCrypt/pull/1

🔥 This fix has been provided through the https://huntr.dev/ bug bounty platform.
